- name: get os name (windows)
  hosts: 192.168.5.*
  gather_facts: false
  tasks:
    - name: run powershell module to get os name
      script: get_osname.ps1
      register: out
    - debug: var=out
